### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by cwh7** [mguideng/gdscrapeR#2]
I've been unable to install this package and I'm not sure what the issue is exactly.  I'm using the latest version of R (R 3.6.0) and all of my packages are updated.  This is what I'm seeing:

> devtools::install_github("mguideng/gdscrapeR")
Downloading GitHub repo mguideng/gdscrapeR@master
Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  Command not found
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by mguideng** [comment]
cwh7 - I believe this error is related to the R infrastructure itself: https://github.com/r-lib/processx#errors
Feel free to e-mail me and let's see if we can work around your error.
