### ISSUE TITLE
StartingError issue

### ISSUE THREAD

**Issue by MetalGearPanda** [mguideng/gdscrapeR#3]
Hi

I'm running both visual studio and R studio and I'm getting this error when using the get_reviews function:

StartingError: 'map_dfr' is not an exported object from 'namespace:purrr'

Thanks

**Comment by mguideng** [comment]
MetalGearPanda - what version of `purrr` are you using? If it's older than v0.2.3, try updating the package to see if that resolves the issue.

**Comment by MetalGearPanda** [comment]
I'm using purrr 0.2.2, so probably explains it. I'm having difficulty getting it updating in VS17 so happy to say that's what my issue was.
